services:
  - type: web
    name: south-inovations-mail-system
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SMTP_HOST
        value: smtp.mailgun.org
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: ADMIN_KEY
        sync: false
