services:
  - type: web
    name: south-inovations-mail-system
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: MAILGUN_FROM
        sync: false
      - key: ADMIN_KEY
        sync: false
